version: 2.1
orbs:
  gomplate: xavientois/gomplate@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    executor: gomplate/gomplate
    steps:
      - run:
          name: "Generate test template"
          command: |
            echo "Hello, {{ .Values.name }}!" > test.txt.tmpl
            echo "name: CircleCI" > Values.yaml
      - gomplate/render:
          template-file: test.txt.tmpl
          output-file: test.txt
          contexts: Values.yaml
      - run:
          name: "Check test template"
          command: |
            cat test.txt
            if [ "$(cat test.txt)" != "Hello, CircleCI!" ]; then
              echo "Test failed"
              exit 1
            fi

workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: xavientois/gomplate
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
