description: This shows the example usage of the orb in order to generate a pipeline for dynamic config

usage:
  version: 2.1
  setup: true

  orbs:
    gomplate: xaventois/gomplate@1.2.3

  workflows:
    use-my-orb:
      jobs:
        - gomplate/render-config:
            template-file: .circleci/continue_config.yml.tmpl
            output-file: .circleci/continue_config.yml
            pre-steps:
              - run:
                  command: |
                    echo '{ "a": "b", list: ["x", "y", "z"] }' > values.yaml
            contexts: values.yaml
